apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: example-interconnect
    interconnect_cr: example-interconnect
  name: example-interconnect
  namespace: myproject
spec:
  host: example-interconnect-myproject.127.0.0.1.nip.io
  port:
    targetPort: port-8672
  to:
    kind: Service
    name: example-interconnect
    weight: 100
  wildcardPolicy: None