{
 "title": "Qpid Dispatch Router Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deliveries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "released_deliveries", "legendFormat": "Released {{instance}}" },
    { "expr": "modified_deliveries", "legendFormat": "Modified {{instance}}" },
    { "expr": "rejected_deliveries", "legendFormat": "Rejected {{instance}}" }
   ]
  },
  {
   "title": "Rate of egress deliveries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(deliveries_egress{job=\"qdmetrics\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "links", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Address Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "addresses ", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Link routes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "link_routes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Auto links",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "auto_links ", "legendFormat": "{{instance}} Auto Links" }
   ]
  }
 ]
}