{
 "title": "Qpid Dispatch Router",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deliveries ingress",
   "type": "graph",
   "description": "Number of deliveries that were sent to it by a sender that is directly attached to the router.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(deliveries_ingress)", "legendFormat": "Deliveries ingress" }
   ]
  },
  {
   "title": "Deliveries egress",
   "type": "graph",
   "description": "Number of deliveries that were sent by the router to a receiver that is directly attached to the router.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deliveries_egress{job='qdmetrics'})",
     "legendFormat": "Deliveries egress"
    }
   ]
  },
  {
   "title": "Link count",
   "type": "graph",
   "description": "Number of links attached to the router node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(links)", "legendFormat": "Link count" }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(connections)", "legendFormat": "Connection count" }
   ]
  },
  {
   "title": "Address Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(addresses{job='qdmetrics'})",
     "legendFormat": "Address count"
    }
   ]
  },
  {
   "title": "Auto links",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(auto_links{job=\"qdmetrics\"})",
     "legendFormat": "Autolinks"
    }
   ]
  },
  {
   "title": "Link routes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(link_routes{job='qdmetrics'})",
     "legendFormat": "Link routes"
    }
   ]
  }
 ]
}